apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

configMapGenerator:
  - name: env-name
    literals:
      - ENV=sample-1
    behavior: replace

nameSuffix: "-1"