apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

configMapGenerator:
  - name: env-name
    literals:
      - ENV=sample-1
    behavior: replace

replacements:
  - source:
      kind: ConfigMap
      name: env-name
      fieldPath: data.ENV
    targets:
      - select:
          kind: Deployment
          name: sample
        fieldPaths:
          - spec.template.spec.containers.0.image
        options:
          delimiter: ":"
          index: 1

nameSuffix: "-1"