apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample
spec:
  selector:
    matchLabels:
      key: sample
  template:
    metadata:
      labels:
        key: sample
    spec:
      containers:
        - name: sample
          image: sample
