apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml

configMapGenerator:
  - name: env-name
    literals:
      - ENV=lab-env
      
images:
- name: sample
  newTag: $(ENV)

vars:
  - name: ENV
    objref:
      name: env-name
      kind: ConfigMap
      apiVersion: v1
    fieldref:
      fieldpath: data.ENV

configurations:
  - varreference.yaml